chore(docker): Optimize dockerfile
toptal/gitignore.io pull request #582
Opened 2022-05-22 07:44 UTC by mritd

Optimize dockerfile

Signed-off-by: kovacs <mritd@linux.com>

2022-06-15 19:49 UTC, filipechagas requested changes
Thank you for this excellent contribution!

I left a couple of comments for you. 
The `--platform=linux/x86-64` will make sure arm users can still build the image.
And the other one seems to be a typo.

Once these are taken care of, the PR is good to be merged 🙂

2022-06-15 19:49 UTC, filipechagas commented on Dockerfile
> +FROM swift:5.6 AS swift-builder
```suggestion
FROM --platform=linux/x86-64 swift:5.6 AS swift-builder
```

2022-06-15 19:49 UTC, filipechagas commented on Dockerfile
> +FROM node:lts AS node-builder
```suggestion
FROM --platform=linux/x86-64 node:lts AS node-builder
```

2022-06-15 19:49 UTC, filipechagas commented on Dockerfile
> +FROM debian:stable-slim
```suggestion
FROM --platform=linux/x86-64 debian:stable-slim
```

2022-06-15 19:49 UTC, filipechagas commented on Dockerfile
> +
```suggestion
RUN git submodule update --init --recursive

```

2022-06-16 05:30 UTC, mritd commented
@filipechagas Can we use `swift:5.6-focal`?

<img width="915" alt="image" src="https://user-images.githubusercontent.com/13043245/173998136-5a26b5fd-3eed-4277-be83-c35a4c5f1cb7.png">


I noticed that it supports both x86 and arm64; this way x86 and arm64 users can not care about the image architecture, and we can also build images with multi-arch support.

2022-06-16 09:48 UTC, mritd commented
I've modified the Dockerfile so that it now supports both x86 and arm64 builds (due to the swift image not supporting other CPU architectures for now).

It is now possible to use the `docker buildx` command to build a multi-CPU architecture-supported image (compatible with the standard `docker build` command), I have pre-built a version: `mritd/gitignore.io`, this image can be used to verify this PR .

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/13043245/174043484-371d05b5-9545-4f5d-aac2-faef8a076239.png">

By the way, I'm not familiar with the swift language, and I don't know if there are other compilation parameters that can optimize the size of the binary compiled by swift; if there are better compilation parameters, I can further optimize the image size.

2022-06-16 17:17 UTC, filipechagas approved these changes
Excellent! I can confirm it builds on ARM with no issues.
Thank you @mritd !!

2022-06-16 17:39 UTC, filipechagas commented on Dockerfile
> +CMD /app/Run serve -e prod -b 0.0.0.0
```suggestion
CMD ["/app/Run", "serve", "-e", "prod", "-b", "0.0.0.0"]
```

2022-06-17 03:47 UTC, mritd commented
@filipechagas I re-edited the CMD command and added some comments so anyone can build their own docker image.

2022-06-17 12:15 UTC, filipechagas requested changes
Thanks for applying the changes @mritd !

I just need to ask you for a final adjustment: The docker-compose commands aren't working anymore. We'll need to remove the `command` line from `docker-compose.yml`

As for `docker-compose-dev.yml` to work, there may be more work to do, probably using a `target`.

2022-06-20 04:09 UTC, mritd commented
I noticed that there is a compose configuration created for development; I created a Dcokerfile (Dockerfile.dev) dedicated to development, but the vapor command fails to execute.

Since I'm not a swift developer, I don't know how to fix the vapor compilation problem (maybe I should downgrade the vapor toolbox version?), @filipechagas can you pass some sample commands to run the project via `vapor run` and some related version information?

This way I can recreate the dockerfile and compose files for development; I think the development environment should meet the following requirements:

- Map the current directory into the container to ensure native code runs
- Recompile swift code every time to ensure consistency
- Cache swift packages as much as possible to avoid repeated downloads

2022-07-13 15:56 UTC, filipechagas commented
Sorry about the delay on this one. I was OOO.

I just realized that docker-compose for development wasn't really working already. So, at this point, I would apply your excellent changes in the `Dockerfile`. We can ditch `Dockerfie.dev` for now and work on that in a separate PR.

WDYT?

2022-07-14 03:38 UTC, mritd commented
I think it's ok, do I need to undo the changes to Dockerfile.dev and docker-compose-dev.yaml?

2022-07-14 11:21 UTC, filipechagas commented
Can you please? That way we avoid misleading people into thinking they're finished.

2022-07-20 03:59 UTC, mritd commented
I have rolled back the changes to dev.

2022-07-20 12:16 UTC, filipechagas approved these changes
Thank you @mritd !

2022-08-20 13:48 UTC, mritd commented
@filipechagas

2022-12-11 11:24 UTC, mritd commented
No response for too long, I close this PR.

2022-12-12 06:54 UTC, konstrybakov commented
Hey @mritd, very sorry for the long review! Is this still something you'd like to be merged? I'll have a quick look and move this forward

2022-12-12 13:31 UTC, konstrybakov approved these changes

2022-12-12 13:32 UTC, merged

2023-05-11 21:10 UTC, rafilkmp3 reviewed
LGTM